name:                collate
version:             0.9.0.0
homepage:            https://github.com/jez/collate
author:              Jake Zimmerman
maintainer:          zimmerman.jake@gmail.com
copyright:           2018 Jake Zimmerman
license:             MIT

extra-source-files:
- README.md
- LICENSE

# Metadata used when publishing your package
synopsis:            Command line filter for collating the top and bottom halves of a file
description:         Please see the README on Github at <https://github.com/jez/collate#readme>
category:            Simple

ghc-options:
- -Wall
- -Wcompat
- -Wmissing-signatures
- -Werror
- -funbox-strict-fields

dependencies:
- base >=4.7 && <5
- text
- split

library:
  source-dirs: src

executables:
  collate:
    main: Main.hs
    source-dirs: app/collate
    dependencies:
    - collate

  uncollate:
    main: Main.hs
    source-dirs: app/uncollate
    dependencies:
    - collate
